// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysAuthIdentityDao is the data access object for the table sys_auth_identity.
// You can define custom methods on it to extend its functionality as needed.
type sysAuthIdentityDao struct {
	*internal.SysAuthIdentityDao
}

var (
	// SysAuthIdentity is a globally accessible object for table sys_auth_identity operations.
	SysAuthIdentity = sysAuthIdentityDao{internal.NewSysAuthIdentityDao()}
)

// Add your custom methods and functionality below.
