// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysAuthProviderDao is the data access object for the table sys_auth_provider.
// You can define custom methods on it to extend its functionality as needed.
type sysAuthProviderDao struct {
	*internal.SysAuthProviderDao
}

var (
	// SysAuthProvider is a globally accessible object for table sys_auth_provider operations.
	SysAuthProvider = sysAuthProviderDao{internal.NewSysAuthProviderDao()}
)

// Add your custom methods and functionality below.
